import type { CSSProperties } from "react";

export const card = (status: "pending" | "accepted" | "rejected"): CSSProperties => ({
  display: "flex",
  gap: 16,
  alignItems: "stretch",
  border: "1px solid var(--border)",
  background: "var(--bg-surface)",
  borderRadius: 10,
  padding: "16px 18px",
  opacity: status === "rejected" ? 0.4 : 1,
});

export const s = {
  body: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column", gap: 10 } satisfies CSSProperties,
  rule: {
    fontSize: 14,
    fontWeight: 600,
    fontStyle: "italic",
    color: "var(--text-primary)",
    cursor: "text",
    lineHeight: 1.4,
  } satisfies CSSProperties,
  ruleInput: {
    fontSize: 14,
    fontWeight: 600,
    fontStyle: "italic",
    color: "var(--text-primary)",
    lineHeight: 1.4,
    width: "100%",
    minHeight: 48,
    padding: "6px 8px",
    border: "1px solid var(--accent)",
    borderRadius: 6,
    background: "var(--bg-surface)",
    outline: "none",
    resize: "vertical",
    fontFamily: "inherit",
  } satisfies CSSProperties,
  ruleEditRow: {
    display: "flex",
    gap: 8,
    justifyContent: "flex-end",
    marginTop: 6,
  } satisfies CSSProperties,
  evidenceBox: {
    border: "1px solid var(--border)",
    background: "var(--bg-secondary)",
    borderRadius: 8,
    overflow: "hidden",
  } satisfies CSSProperties,
  evidenceHeader: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "6px 10px",
    fontFamily: "var(--font-mono)",
    fontSize: 12,
    color: "var(--text-secondary)",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  evidenceSnippet: {
    fontFamily: "var(--font-mono)",
    fontSize: 12,
    lineHeight: 1.5,
    padding: "10px 12px",
    margin: 0,
    color: "var(--text-primary)",
    whiteSpace: "pre",
    overflowX: "auto",
  } satisfies CSSProperties,
  confRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  confLabel: { width: 80 } satisfies CSSProperties,
  confValue: { width: 36, textAlign: "right" as const, fontVariantNumeric: "tabular-nums" } satisfies CSSProperties,
  actions: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    width: 130,
    flexShrink: 0,
  } satisfies CSSProperties,
} as const;
