import type { CSSProperties } from "react";

export const s = {
  wrap: { padding: "20px 24px 40px", maxWidth: 1040 } satisfies CSSProperties,
  head: { display: "flex", alignItems: "flex-start", gap: 12, marginBottom: 18 } satisfies CSSProperties,
  title: { fontSize: 16, fontWeight: 600 } satisfies CSSProperties,
  subtitle: { fontSize: 13, color: "var(--text-muted)", marginTop: 4 } satisfies CSSProperties,
  flexGrow: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  metricRow: { display: "flex", gap: 12, marginBottom: 16, flexWrap: "wrap" } satisfies CSSProperties,
  helpLine: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    fontSize: 12.5,
    color: "var(--text-muted)",
    lineHeight: 1.5,
    marginBottom: 8,
  } satisfies CSSProperties,
  section: { marginTop: 26 } satisfies CSSProperties,
  sectionHead: { display: "flex", alignItems: "center", gap: 10, marginBottom: 12 } satisfies CSSProperties,
  // Run history. Grid, not a table element — this codebase has no Table primitive.
  runsTable: { display: "flex", flexDirection: "column", gap: 2 } satisfies CSSProperties,
  runsHeadRow: {
    display: "grid",
    gridTemplateColumns: "28px 2fr 0.8fr 0.8fr 0.8fr 0.8fr 0.8fr",
    gap: 10,
    padding: "6px 12px",
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  runsRow: {
    display: "grid",
    gridTemplateColumns: "28px 2fr 0.8fr 0.8fr 0.8fr 0.8fr 0.8fr",
    gap: 10,
    alignItems: "center",
    padding: "10px 12px",
    fontSize: 13,
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  trendWrap: {
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    borderRadius: 9,
    padding: 16,
  } satisfies CSSProperties,
  driftedList: { display: "flex", flexDirection: "column", gap: 4, marginTop: 10 } satisfies CSSProperties,
  driftedRow: { display: "flex", alignItems: "center", gap: 8, fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  headline: { display: "flex", alignItems: "baseline", gap: 8, flexWrap: "wrap" } satisfies CSSProperties,
  headlineCount: { fontSize: 15, fontWeight: 600 } satisfies CSSProperties,
  headlineFrom: { fontSize: 12.5, color: "var(--text-muted)" } satisfies CSSProperties,
  caseList: { display: "flex", flexDirection: "column", gap: 8, marginTop: 12 } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "12px 14px",
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-surface)",
    flexWrap: "wrap",
  } satisfies CSSProperties,
  rowMain: { display: "flex", flexDirection: "column", gap: 4, flex: 1, minWidth: 200 } satisfies CSSProperties,
  rowTitleLine: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" } satisfies CSSProperties,
  rowName: { fontSize: 13.5, fontWeight: 600, color: "var(--text-primary)" } satisfies CSSProperties,
  rowMeta: { display: "flex", alignItems: "center", gap: 8, fontSize: 12, color: "var(--text-muted)", flexWrap: "wrap" } satisfies CSSProperties,
  rowActions: { display: "flex", alignItems: "center", gap: 6, flexShrink: 0 } satisfies CSSProperties,
  statusText: (color: string): CSSProperties => ({
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12.5,
    fontWeight: 600,
    color,
  }),
  iconBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 6,
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    color: "var(--text-muted)",
    cursor: "pointer",
  } satisfies CSSProperties,
  progressWrap: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginBottom: 16,
    padding: "10px 14px",
    border: "1px solid var(--accent)",
    borderRadius: 8,
    background: "var(--accent-bg)",
  } satisfies CSSProperties,
} as const;
