import type { CSSProperties } from "react";

export const s = {
  wrap: { padding: "20px 24px 40px", maxWidth: 920 } satisfies CSSProperties,
  head: { display: "flex", alignItems: "center", gap: 12, marginBottom: 6 } satisfies CSSProperties,
  title: { fontSize: 16, fontWeight: 600 } satisfies CSSProperties,
  note: {
    fontSize: 13,
    color: "var(--text-muted)",
    margin: "10px 0 16px",
    display: "flex",
    alignItems: "center",
    gap: 8,
  } satisfies CSSProperties,
  estimateRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 14,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  search: { marginBottom: 14 } satisfies CSSProperties,
  row: (dragging: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 14px",
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: dragging ? "var(--bg-secondary)" : "var(--bg-surface)",
    marginBottom: 6,
  }),
  handle: (draggable: boolean): CSSProperties => ({
    cursor: draggable ? "grab" : "default",
    color: draggable ? "var(--text-muted)" : "var(--border-strong)",
    display: "inline-flex",
    padding: 2,
  }),
  moveBtns: { display: "flex", flexDirection: "column", gap: 1 } satisfies CSSProperties,
  moveBtn: {
    background: "none",
    border: "none",
    color: "var(--text-muted)",
    cursor: "pointer",
    padding: 1,
    display: "inline-flex",
  } satisfies CSSProperties,
  fileInfo: { display: "flex", flexDirection: "column", gap: 2, minWidth: 0 } satisfies CSSProperties,
  filename: {
    fontFamily: "var(--font-mono)",
    fontSize: 13,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  folder: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  flexGrow: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  previewBody: { display: "flex", flexDirection: "column", gap: 14 } satisfies CSSProperties,
  previewMeta: { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" } satisfies CSSProperties,
} as const;
